### ISSUE TITLE
what effect of  rgan_network.train_full_model?

### ISSUE THREAD

**Issue by eeric** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#10]
Training the generator G and the discriminator D  should use different data in model.py, shouldn't it?
But, the same images were used to train G and D in model.py.

**Comment by titu1994** [comment]
Only a small subset is used to pretrain the discriminator. Around 5000 samples or so out of the 80k image samples. I'll be fixing that later. It's not necessary to use completely different datasets for pretrain in the discriminator.

**Comment by titu1994** [comment]
As to the full training, I am following the normal process of updating the discriminator with the generator weights untrained and then train the generator with the discriminators weights untrained.
