### ISSUE TITLE
Still error when checking : (None, 3, 32, 32) but got array with shape (1, 3, 128, 128)

### ISSUE THREAD

**Issue by eeric** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#12]
Yes, I have use a new version, but it occurs still error following,
Exception: Error when checking : expected x_generator to have shape (None, 3, 32, 32) but got array with shape (1, 3, 128, 128)

That contradicts Scaling 32x32 in srgan_network = SRGANNetwork(img_width=32, img_height=32, batch_size=1) in 711th line, downscale to 96x96 and upscale to 384x384 in model.py?
So that is modified 6464 in srgan_network = SRGANNetwork(img_width=32, img_height=32, batch_size=1), isn't it?

**Comment by titu1994** [comment]
Sorry that was my mistake. I was working on the dev branch and forgot to merge onto the master branch. Now the master branch should contain the updated models.py.

Sorry for the trouble
