### ISSUE TITLE
A problem occured when I execute the model.py

### ISSUE THREAD

**Issue by wangtingwei1993** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#14]
Hello titu1994,When I execute the model.py to plot the pretrain_model and an error occur, just as "ValueError: Dimension size must be evenly divisible by 3 but is 32
        Number of ways to split should evenly divide the split dimension"
I think it is caused by the input size but I have no idea how to fix it,I wonder if you could give me some suggestion? THX

**Comment by ghost** [comment]
using theano backend is ok.

**Comment by titu1994** [comment]
I haven't gotten around to make this model compatible with Tensorflow backend yet. I am fixing a few bugs in Theano implementation first.
