### ISSUE TITLE
Something wrong when I train the full-model

### ISSUE THREAD

**Issue by wangtingwei1993** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#15]
I can pre-train the Generator and Discriminator separately but When I train the full-model ,Something wrong,just says:
    theano.gof.fg.MissingInputError: ("An input of the graph, used to compute Elemwise{true_div,no_inplace}(x_discriminator, DimShuffle{x,x,x,x}.0), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", x_discriminator)
    Someone else maybe have the same problem, I wonder if you have any idea to fix it or may be I train the full-model in a wrong way.

**Comment by titu1994** [comment]
I have not been able to train the full model. However the error I get is not MissingInputError but a recursion limit exceeded error. Are you using the master branch? If i remember, the dev and master branch were currently at par with each other so try either.

In either case, the full model cannot be trained right now. I am a little busy with preparing to leave for my Masters at UIC so I won't be able to fix it for some time. If you can, then please do send a PR.
