### ISSUE TITLE
AssertionError: "assert K.ndim(x) == 4"

### ISSUE THREAD

**Issue by maple1217** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#18]
Thank you very much for your work. It is great!

When I tried to run your code, I met the assert error "assert K.ndim(x) == 4".
It seems that the dimension of the input to the activity regularizer is not 4.

I couldn't figure out the reason. Could you please give me some suggestions?

Thank you very much!

**Comment by titu1994** [comment]
Could you give me the stack trace of where this error originated from ? I've used that assertion in many places.

**Comment by maple1217** [comment]
Thank you for your reply.
I have found the reason was that the version of Keras was too old.

I have another question.
Has the weight file "SRGAN.h5" in this project already been trained?
Could I delete it and train it by myself?

**Comment by titu1994** [comment]
The weight file SRGAN.h5 is the pretraijed model. Note however, that it causes checkerboard artifacts at the moment and is not recommended for general use. 

You can delete and train a new model, bit be careful. In the first few iterations see if you are getting solid core validation images. If so, stop training and restart with randomly initialized weights. It may take a few tried but eventually you should be able to see validation images which are similar to the real images. At that point, let it continue training.
