### ISSUE TITLE
Different block config than the original paper

### ISSUE THREAD

**Issue by islamtashfiq** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#20]
In each resnet block in the original paper there is only one leaky relu but in yours there are two. Could you verify that?

**Comment by titu1994** [comment]
Could you tell me where on the original paper it is mentioned as 1 LeakyRelu?

**Comment by islamtashfiq** [comment]
In Figure 4 there is only one relu (yellow) in each block. Furthermore they mentioned that their residual block is inspired by [fast style transfer](https://cs.stanford.edu/people/jcjohns/papers/fast-style/fast-style-supp.pdf
) in which they used 1 relu per block.

**Comment by titu1994** [comment]
Sorry for the delay. 

It was my mistake in assuming that a LeakyRelu should always follow a Batch norm. I've pushed a commit to fix it. 

Thanks for catching the error.
