### ISSUE TITLE
What's the turn of train models?

### ISSUE THREAD

**Issue by dlongry** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#22]
Thank you for this great work. but I have a doubt when I using your model.py to train:
Should I pretrain the SR network at first,then pretrain the Discriminator network. And at last, train the full network?

or just directly train the full  network?

@titu1994

**Comment by titu1994** [comment]
Follow the commented out procedure. First pretraijed the Discriminator then
the SRGAN. The pre training for SRGAN was a test to see if it was learning
anything on its own or not.

I don't really think this works to be honest. If you are hoping to get a
upscaled image then i suggest going for the theano implementation by
jcjohnson.


Somshubra Majumdar

**Comment by dlongry** [comment]
Thanks a lot. And could you give me the link to SRGAN implementation by jcjohnsom？ @titu1994

**Comment by titu1994** [comment]
Just search in Google

Somshubra Majumdar

**Comment by dlongry** [comment]
Thanks for quickly reply. In fact，I have searched it in Google before I update my quetion. Maybe I used the fake Google. e... I can't find the SRGAN implementation by jcjohnsom that you said. so...Could you give me a hand?Thanks.@titu1994

**Comment by ahundt** [comment]
https://github.com/jcjohnson/torch-rnn

**Comment by titu1994** [comment]
Sorry I was busy with an assignment deadline at that time. I made a mistake with the name. Its https://github.com/alexjc/neural-enhance.

Alexjc rather than jcjohnson. Sorry for the confusion.

**Comment by dlongry** [comment]
I get it.  Thank you a lot for replying to me from your busy schedule.
