### ISSUE TITLE
The image quality is not good as expected

### ISSUE THREAD

**Issue by cheyenlu** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#24]
I am not sure if the issue is caused by weight or implementation. Currently, I use pretrained weight weights/SRGAN.h5 for testing. However, the image is blurred and color is different from original image. I wonder if you can share the weight file you are using now? 
Generated image
![image](https://cloud.githubusercontent.com/assets/6611408/24785580/344c9ce2-1b29-11e7-8ff1-36d23fff47ab.png)
Original image
![image](https://cloud.githubusercontent.com/assets/6611408/24785586/42a51742-1b29-11e7-950c-3eae36d01a9c.png)

**Comment by titu1994** [comment]
I actually have stopped working on this sometime back. Sorry about that but
I don't have any better model at the moment.

If upscaling is your goal, I suggest looking up Neural Enhance. It is based
on this paper.

Somshubra Majumdar

**Comment by cheyenlu** [comment]
Thanks!! I will check this repo out. :)
