### ISSUE TITLE
An error in keras_op.py

### ISSUE THREAD

**Issue by yutianhang** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#25]
Line 5:
from keras.engine.training import objectives, standardize_input_data, slice_X, \
    standardize_sample_weights, standardize_class_weights, standardize_weights, check_loss_and_target_compatibility

There has not objectives function in  keras/engine/training.py
Please check it.

**Comment by doantientai** [comment]
I had the same problem and fixed by using Keras 1.2.0

**Comment by titu1994** [comment]
Yeah I've not updated the code past Keras 1.2.2. 

For now, since I'm busy with course work and lectures, I'm putting this project on hiatus. Sorry about that.
