### ISSUE TITLE
A Simple Confusion Regarding the Description Provided for Training the Full Model 

### ISSUE THREAD

**Issue by rmalav15** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#27]
Hey @titu1994 

Much much thanks for this great implementation.

I am slightly confused with following two lines.

> To train the full network (**Does NOT work properly right now, Discriminator is not correctly trained**):

(Last lines in **USAGE**)
and

> **Properly train** SRGAN (SR ResNet + VGG + Discriminator) model. 

(**Right marked** in **PLANS**)

Can you please let me know the current situation of full training?  
Is there any implementation fault for full training or just it doesn't work properly after following everything correctly?  

Thanks.

**Comment by titu1994** [comment]
I've stopped working on the code, but i think the Discriminator now trains properly. I forgot to update the comment in the usage.

Even so, it's performance is abysmal. I suggest taking a look at neural enhance. It is the same model, but has pretrained weights and working scripts and docker installs.
