### ISSUE TITLE
missing "sr_resnet_weights.h5" weights h5 files

### ISSUE THREAD

**Issue by JustinhoCHN** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#28]
In the benchmark_test.py line 146, the network want to load the sr_resnet_weights.h5 file, but cannot find it in weights/ document, can you please release the pre-trained weights? I want to test the model with some of my images. Thanks a lot.

**Comment by titu1994** [comment]
Sorry, I don't have the weights. You'll need to train on your own. The implementation is also not correct, in that it generates a lot of tile like artifacts. I suggest you use neural enhance  l
