### ISSUE TITLE
how to run test?

### ISSUE THREAD

**Issue by eeric** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#5]
--python benchmark_test.py

Using Theano backend.
Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled, cuDNN 4007)
SR ResNet model weights loaded.
Testing model on Set 5 Validation images
Traceback (most recent call last):
File "benchmark_test.py", line 299, in 
test_set5(sr_resnet_test.model, img_width=img_width, img_height=img_height)
File "benchmark_test.py", line 45, in test_set5
model, total_psnr, "set5", 5)

NameError: global name 'model' is not defined

**Comment by titu1994** [comment]
Sorry for the late reply. Was working on another project.

For the error, the following 3 lines must be executed first:

```
img_width = img_height = 64
sr_resnet_test = SRResNetTest(img_width=img_width, img_height=img_height, batch_size=1)
sr_resnet_test.build_model(load_weights=False)
```

That loads the definition of `sr_resnet_test.model` in the tests

**Comment by eeric** [comment]
modified following:

35 line:  def test_set5(Model, img_width=32, img_height=32, batch_size=1):
51 line:  def test_set14( Model, img_width=32, img_height=32, batch_size=1):
66 line:  def test_bsd100(Model, img_width=32, img_height=32, batch_size=1):
148 line:  def build_model(self, load_weights=False) :
291 line:  img_width = img_height = 64
293 line:  sr_resnet_test = SRResNetTest(img_width=img_width, img_height=img_height, batch_size=1)
294 line:  sr_resnet_test.build_model(load_weights=False)

so running result  is training, but that isn't to need for me.

I need to know that how test your model trained on verification database, or how to test my model trained on verification database.

**Comment by titu1994** [comment]
The code for 3 verification datasets has been provided (Set5, Set14 and BSD100). See the code for that. Mainly you have to call the _test_loop(...) function which handles the testing procedure.

**Comment by eeric** [comment]
so in 299th line: test_set5(sr_resnet_test.model, img_width=img_width, img_height=img_height), in which where is it to sr_resnet_test.model ? or 
how to load  sr_resnet_test.model?

**Comment by titu1994** [comment]
`sr_resnet_test.build_model(load_weights=True)` <---- This line builds the model, thereby loading the sr_resnet_test.model

I meant that if you want to create your own validation or test dataset then use the test_set5(...) code as an example and write your own code.

**Comment by eeric** [comment]
as your advice, so error following

Using Theano backend.
Using gpu device 0: GeForce GTX 980 Ti (CNMeM is enabled with initial size: 10.0% of memory, cuDNN 4007)
SR ResNet model weights loaded.
Testing model on Set 5 Validation images
Traceback (most recent call last):
  File "benchmark_test.py", line 299, in <module>
    test_set5(sr_resnet_test.model, img_width=img_width, img_height=img_height)
  File "benchmark_test.py", line 45, in test_set5
    model, total_psnr, "set5", 5)
NameError: global name 'model' is not defined

**Comment by eeric** [comment]
--Tested successfully when all 'model' variables are replaced of 'Model' in benchmark_test.py, details following,
 --python benchmark_test.py

Using Theano backend.
SR ResNet model weights loaded.
Testing model on Set 5 Validation images
Found 5 images belonging to 1 classes.
Time required : 11.19. Average validation PSNR over 1 samples = 25.00
Time required : 0.74. Average validation PSNR over 1 samples = 25.80
Time required : 0.77. Average validation PSNR over 1 samples = 21.62
Time required : 0.76. Average validation PSNR over 1 samples = 25.77
Time required : 0.74. Average validation PSNR over 1 samples = 26.01
('Average PSNR of Set5 validation images : ', 24.83958517392562)
()
