### ISSUE TITLE
where is it to val_images in benchmark.py?

### ISSUE THREAD

**Issue by eeric** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#7]
1.Images from val_images aren't like same to set5 or set14 or bsd100, are they?

2.Where is effect image generated by your model for As an image from set5?

**Comment by titu1994** [comment]
The images in val_images are comparisons on the upscaled image by SRResNet and the original validation image. 

The validation images are copies of the validation images in Set5, Set14 and BSD100
