### ISSUE TITLE
when using tensorflow it has some errors

### ISSUE THREAD

**Issue by Harick1** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#8]
Firstly, when I use theano, I can successfully run your benchmark_test.py.
When I am trying tensorflow, in the layers.py, the function   depth_to_scale_tf(), tf.split(3,3,input) has some errors listed as follows:
 Number of ways to split should evenly divide the split dimension for 'split' (op: 'Split') with input shapes: [], [?,3,64,256].
The images are used in Set5.
What's more, i just change the ./keras/keras.json when I am trying tensorflow

**Comment by titu1994** [comment]
This code has not been tested on Tensorflow, since I am on Windows. That code is from another implementation. If you can find some fix, please add a PR.
