### ISSUE TITLE
 Updating the generator G and the discriminator D with the same batch data, isn't it?

### ISSUE THREAD

**Issue by eeric** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#9]
At present, it was describedthat the G and D were updated in the same Theano update and with the same batch data in enhance.py, so the effect of discriminator D was restricted.

It wasn't done to training G and D in separate updates with different data in enhance.py, was it?

**Comment by titu1994** [comment]
@eeric You are confusing this repository with the alexjc repository. This one doesnt have any enhance.py
